Create database [TestCreator]
GO
USE [TestCreator]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblANSWER](
	[id_answer] [int] IDENTITY(1,1) NOT NULL,
	[title] [varchar](255) NOT NULL,
	[group_name] [int] NULL,
	[is_true] [tinyint] NOT NULL,
 CONSTRAINT [pk_answer_id] PRIMARY KEY CLUSTERED 
(
	[id_answer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, 
IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, 
ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblAUTHOR](
	[id_author] [int] IDENTITY(1,1) NOT NULL,
	[test_id] [int] NOT NULL,
	[user_id] [int] NOT NULL,
 CONSTRAINT [pk_author_id] PRIMARY KEY CLUSTERED 
(
	[id_author] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblGROUP](
	[id_group] [int] IDENTITY(1,1) NOT NULL,
	[group_name] [varchar](30) NOT NULL,
	[group_password] [varchar](30) NOT NULL,
	[security_status] [varchar](30) NOT NULL,
	[invitation_link] [varchar](50) NOT NULL,
 CONSTRAINT [pk_group_id] PRIMARY KEY CLUSTERED 
(
	[id_group] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblGROUP_TEST](
	[id_group_test] [int] IDENTITY(1,1) NOT NULL,
	[group_id] [int] NOT NULL,
	[test_id] [int] NOT NULL,
 CONSTRAINT [pk_groupTest_id] PRIMARY KEY CLUSTERED 
(
	[id_group_test] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblPASSED_ANSWER](
	[id_passed_answer] [int] IDENTITY(1,1) NOT NULL,
	[answer] [nvarchar](50) NOT NULL,
	[question_id] [int] NOT NULL,
 CONSTRAINT [PK_tblPASSED_ANSWER] PRIMARY KEY CLUSTERED 
(
	[id_passed_answer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblPASSED_TEST](
	[id_passed_test] [int] IDENTITY(1,1) NOT NULL,
	[test_id] [int] NOT NULL,
	[result] [float] NOT NULL,
 CONSTRAINT [pk_passedTest_id] PRIMARY KEY CLUSTERED 
(
	[id_passed_test] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblPASSED_TEST_ANSWER](
	[id_passed_test_answer] [int] IDENTITY(1,1) NOT NULL,
	[passed_answer_id] [int] NOT NULL,
	[passed_test_id] [int] NOT NULL,
 CONSTRAINT [pk_passedTestAnswer_id] PRIMARY KEY CLUSTERED 
(
	[id_passed_test_answer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblQUESTION](
	[id_question] [int] IDENTITY(1,1) NOT NULL,
	[title] [varchar](255) NOT NULL,
	[mark] [int] NOT NULL,
	[num_true_answer] [int] NOT NULL,
	[is_check_box] [tinyint] NOT NULL,
 CONSTRAINT [pk_question_id] PRIMARY KEY CLUSTERED 
(
	[id_question] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblQUESTION_ANSWER](
	[id_question_answer] [int] IDENTITY(1,1) NOT NULL,
	[question_id] [int] NOT NULL,
	[answer_id] [int] NOT NULL,
 CONSTRAINT [pk_questionAnswer_id] PRIMARY KEY CLUSTERED 
(
	[id_question_answer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblTEST](
	[id_test] [int] IDENTITY(1,1) NOT NULL,
	[title] [varchar](255) NOT NULL,
 CONSTRAINT [pk_test_id] PRIMARY KEY CLUSTERED 
(
	[id_test] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblTEST_QUESTION](
	[id_test_question] [int] IDENTITY(1,1) NOT NULL,
	[test_id] [int] NOT NULL,
	[question_id] [int] NOT NULL,
 CONSTRAINT [pk_testQuestion_id] PRIMARY KEY CLUSTERED 
(
	[id_test_question] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblUSER](
	[id_user] [int] IDENTITY(1,1) NOT NULL,
	[first_name] [varchar](30) NOT NULL,
	[surname] [varchar](30) NOT NULL,
	[last_name] [varchar](30) NULL,
	[user_login] [varchar](30) NOT NULL,
	[user_password] [varchar](30) NOT NULL,
	[user_activation_code] [varchar](50) NULL,
	[user_email] [varchar](50) NOT NULL,
 CONSTRAINT [pk_user_id] PRIMARY KEY CLUSTERED 
(
	[id_user] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblUSER_GROUP](
	[id_user_group] [int] IDENTITY(1,1) NOT NULL,
	[user_id] [int] NOT NULL,
	[group_id] [int] NOT NULL,
	[is_admin] [tinyint] NOT NULL,
 CONSTRAINT [pk_userGroup_id] PRIMARY KEY CLUSTERED 
(
	[id_user_group] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblUSER_PASSED_TEST](
	[id_user_passed_test] [int] IDENTITY(1,1) NOT NULL,
	[user_id] [int] NOT NULL,
	[passed_test_id] [int] NOT NULL,
 CONSTRAINT [pk_userPassedTest_id] PRIMARY KEY CLUSTERED 
(
	[id_user_passed_test] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblAUTHOR]  WITH CHECK ADD  CONSTRAINT [fk_author_test] FOREIGN KEY([test_id])
REFERENCES [dbo].[tblTEST] ([id_test])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblAUTHOR] CHECK CONSTRAINT [fk_author_test]
GO
ALTER TABLE [dbo].[tblAUTHOR]  WITH CHECK ADD  CONSTRAINT [fk_author_user] FOREIGN KEY([user_id])
REFERENCES [dbo].[tblUSER] ([id_user])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblAUTHOR] CHECK CONSTRAINT [fk_author_user]
GO
ALTER TABLE [dbo].[tblGROUP_TEST]  WITH CHECK ADD  CONSTRAINT [fk_groupTest_group] FOREIGN KEY([group_id])
REFERENCES [dbo].[tblGROUP] ([id_group])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblGROUP_TEST] CHECK CONSTRAINT [fk_groupTest_group]
GO
ALTER TABLE [dbo].[tblGROUP_TEST]  WITH CHECK ADD  CONSTRAINT [fk_groupTest_test] FOREIGN KEY([test_id])
REFERENCES [dbo].[tblTEST] ([id_test])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblGROUP_TEST] CHECK CONSTRAINT [fk_groupTest_test]
GO
ALTER TABLE [dbo].[tblPASSED_ANSWER]  WITH CHECK ADD  CONSTRAINT [FK_tblPASSED_ANSWER_tblQUESTION] FOREIGN KEY([question_id])
REFERENCES [dbo].[tblQUESTION] ([id_question])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblPASSED_ANSWER] CHECK CONSTRAINT [FK_tblPASSED_ANSWER_tblQUESTION]
GO
ALTER TABLE [dbo].[tblPASSED_TEST]  WITH CHECK ADD  CONSTRAINT [fk_passedTest_test] FOREIGN KEY([test_id])
REFERENCES [dbo].[tblTEST] ([id_test])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblPASSED_TEST] CHECK CONSTRAINT [fk_passedTest_test]
GO
ALTER TABLE [dbo].[tblPASSED_TEST_ANSWER]  WITH CHECK ADD  CONSTRAINT [FK_tblPASSED_TEST_ANSWER_tblPASSED_ANSWER] FOREIGN KEY([passed_answer_id])
REFERENCES [dbo].[tblPASSED_ANSWER] ([id_passed_answer])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblPASSED_TEST_ANSWER] CHECK CONSTRAINT [FK_tblPASSED_TEST_ANSWER_tblPASSED_ANSWER]
GO
ALTER TABLE [dbo].[tblPASSED_TEST_ANSWER]  WITH CHECK ADD  CONSTRAINT [FK_tblPASSED_TEST_ANSWER_tblPASSED_TEST] FOREIGN KEY([passed_test_id])
REFERENCES [dbo].[tblPASSED_TEST] ([id_passed_test])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblPASSED_TEST_ANSWER] CHECK CONSTRAINT [FK_tblPASSED_TEST_ANSWER_tblPASSED_TEST]
GO
ALTER TABLE [dbo].[tblQUESTION_ANSWER]  WITH CHECK ADD  CONSTRAINT [fk_questionAnswer_answer] FOREIGN KEY([answer_id])
REFERENCES [dbo].[tblANSWER] ([id_answer])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblQUESTION_ANSWER] CHECK CONSTRAINT [fk_questionAnswer_answer]
GO
ALTER TABLE [dbo].[tblQUESTION_ANSWER]  WITH CHECK ADD  CONSTRAINT [fk_questionAnswer_question] FOREIGN KEY([question_id])
REFERENCES [dbo].[tblQUESTION] ([id_question])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblQUESTION_ANSWER] CHECK CONSTRAINT [fk_questionAnswer_question]
GO
ALTER TABLE [dbo].[tblTEST_QUESTION]  WITH CHECK ADD  CONSTRAINT [fk_testQuestion_question] FOREIGN KEY([question_id])
REFERENCES [dbo].[tblQUESTION] ([id_question])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblTEST_QUESTION] CHECK CONSTRAINT [fk_testQuestion_question]
GO
ALTER TABLE [dbo].[tblTEST_QUESTION]  WITH CHECK ADD  CONSTRAINT [fk_testQuestion_test] FOREIGN KEY([test_id])
REFERENCES [dbo].[tblTEST] ([id_test])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblTEST_QUESTION] CHECK CONSTRAINT [fk_testQuestion_test]
GO
ALTER TABLE [dbo].[tblUSER_GROUP]  WITH CHECK ADD  CONSTRAINT [fk_userGroup_group] FOREIGN KEY([group_id])
REFERENCES [dbo].[tblGROUP] ([id_group])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblUSER_GROUP] CHECK CONSTRAINT [fk_userGroup_group]
GO
ALTER TABLE [dbo].[tblUSER_GROUP]  WITH CHECK ADD  CONSTRAINT [fk_userGroup_user] FOREIGN KEY([user_id])
REFERENCES [dbo].[tblUSER] ([id_user])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblUSER_GROUP] CHECK CONSTRAINT [fk_userGroup_user]
GO
ALTER TABLE [dbo].[tblUSER_PASSED_TEST]  WITH CHECK ADD  CONSTRAINT [fk_userPassedTest_passedTest] FOREIGN KEY([passed_test_id])
REFERENCES [dbo].[tblPASSED_TEST] ([id_passed_test])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblUSER_PASSED_TEST] CHECK CONSTRAINT [fk_userPassedTest_passedTest]
GO
ALTER TABLE [dbo].[tblUSER_PASSED_TEST]  WITH CHECK ADD  CONSTRAINT [fk_userPassedTest_user] FOREIGN KEY([user_id])
REFERENCES [dbo].[tblUSER] ([id_user])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tblUSER_PASSED_TEST] CHECK CONSTRAINT [fk_userPassedTest_user]
GO

